name: vitis-ai-pytorch

channels:
  - pytorch
  - conda-forge
  - anaconda

dependencies:
  - python=3.7
  - pytorch_nndct_cpu
  - pyyaml
  - jupyter
  - ipywidgets
  - dill
  - progressbar2
  - pytest
  - scikit-learn
  - pandas
  - matplotlib
  - vaic
  - vart
  - vai_utf
  - pip
  - pip:
    - https://download.pytorch.org/whl/cpu/torchvision-0.11.2%2Bcpu-cp37-cp37m-linux_x86_64.whl
    - ck
    - orderedset
    - opencv-contrib-python

